# Generated by Django 4.2.3 on 2023-07-11 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citasmedicas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='alergia',
            field=models.CharField(default=' ', max_length=100),
        ),
        migrations.AddField(
            model_name='paciente',
            name='correo',
            field=models.CharField(default=' ', max_length=100),
        ),
        migrations.AlterField(
            model_name='admin1',
            name='contraseña',
            field=models.CharField(max_length=100),
        ),
    ]
